Repository mobu-of-the-world/mobu, pull requests merged in 2021-05, with the labels that each got.

#111 Assign maintainers as reviewer instead of by name
  .github/dependabot.yml
Labels: automerge

#113 Trivial bugfix: don't prohibit username with spaces
  src/pages/AppContainer.tsx
Labels: bug

#115 Colorize the buttons for when it's hovered
  src/atoms/Button.css
Labels: enhancement
